# Generated by Django 3.1.4 on 2023-02-13 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_auto_20230213_2320'),
        ('submissions', '0002_submissions_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissions',
            name='assignment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='assignments.assignments'),
        ),
    ]
