# Generated by Django 3.1.4 on 2023-02-13 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_auto_20230213_2320'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('submissions', '0003_auto_20230213_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissions',
            name='assignment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='assignments.assignments', verbose_name='Assignment'),
        ),
        migrations.AlterField(
            model_name='submissions',
            name='submitter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Submitter'),
        ),
    ]
