# Generated by Django 3.1.4 on 2023-02-12 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignments',
            old_name='course',
            new_name='course_id',
        ),
    ]
